###
# Pulls the code from Pypi
#
---
- name: copy the celery systemd service file in place
  become: yes
  template: src=celery.service.j2 dest=/lib/systemd/system/celery.service

- name: enable and start celery service
  become: yes
  service:
    name: celery
    state: started
    enabled: yes
